# Generated by Django 4.0.6 on 2022-10-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hetul11', '0003_remove_product_category_remove_product_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amazon_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='filpkart_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
